### ISSUE TITLE
Support for serverless deployments

### ISSUE THREAD

**Issue by dsmileyephe** [scottie1984/swagger-ui-express#140]
I recently was pulling my hair out trying to get `swagger-ui-express` to work with a serverless API that is deployed to API gateway. The biggest problem is that that the routes for the dependent files served up via `swagger-ui-dist` have to be exposed explicitly as routes in the `serverless.ym`l file. For example:
```
Docs:
        handler: src/index.handler
        events:
            - http:
                path: /api-docs/{proxy+}
                method: get
                cors:
                    origin: '*'
                    headers:
                      - Content-Type
                      - Authorization
                      - x-amzn-trace-id
        warmup: true
```
In this example we are taking advantage of greedy paths defined [here](https://aws.amazon.com/blogs/aws/api-gateway-update-new-features-simplify-api-development/).
For people not familiar with serving static files in express they might overlook this. Can you update your documentation for users of serverless and include an example like this?
