### ISSUE TITLE
Array type in query param (multi)

### ISSUE THREAD

**Issue by HailoMYM** [scottie1984/swagger-ui-express#227]
How can I make a query parameter that must be an array using collectionFormat: multi

My parameter definition is as follow
```
name: id
in: query
required: true
schema:
    type: array
    items:
        type: integer
    collectionFormat: multi
```
