### ISSUE TITLE
SyntaxError: Unexpected token ...

### ISSUE THREAD

**Issue by bozzltron** [scottie1984/swagger-ui-express#95]
I get a Bad Request error when trying to authenticate into the swagger docs.  I found this stack trace.

"SyntaxError: Unexpected token ...
    at Object.getConfigs (https://mysite/docs/swagger-ui-bundle.js:82:147614)
    at authorize (https://mysite/docs/swagger-ui-bundle.js:82:35474)
    at Object.i (https://mysite/docs/swagger-ui-bundle.js:29:14815)
    at s (https://mysite/docs/swagger-ui-bundle.js:29:10767)
    at Object.executeDispatchesInOrder (https://mysite/docs/swagger-ui-bundle.js:29:11496)
    at p (https://mysite/docs/swagger-ui-bundle.js:13:50250)
    at h (https://mysite/docs/swagger-ui-bundle.js:13:50376)
    at Array.forEach (<anonymous>)
    at e.exports (https://mysite/docs/swagger-ui-bundle.js:70:65262)
    at Object.processEventQueue (https://mysite/docs/swagger-ui-bundle.js:13:51768)"

**Comment by bozzltron** [comment]
It looks like its not picking up my security definitions.  I only have oauth2 defined.  I use yaml format.

```
securityDefinitions:
  oauth:
    type: oauth2
    tokenUrl: /oauth/token
    flow: application
security:
  - oauth: []
```
